name: Daily Video Rebuild

on:
  schedule:
    # This runs at 3:00 AM UTC every day.
    - cron: '0 3 * * *'
  
  # This line adds a button to run the job manually
  workflow_dispatch:

jobs:
  build:
    name: Trigger Netlify Rebuild
    runs-on: ubuntu-latest
    steps:
      - name: Ping Netlify Build Hook
        # This is the corrected line:
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK_URL }}
